# Generated by Django 3.2.3 on 2021-05-13 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('tytul', models.TextField()),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(choices=[('Motocykl', 'Motocykl'), ('Osobowy', 'Osobowy'), ('Ciężarowy', 'Ciężarowy')], max_length=9)),
                ('marka', models.TextField()),
                ('model', models.TextField()),
                ('rok_produkcji', models.IntegerField()),
                ('przebieg', models.IntegerField()),
                ('pojemnosc_skokowa', models.IntegerField()),
                ('moc', models.IntegerField()),
                ('rodzaj_paliwa', models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('LPG', 'LPG')], max_length=8)),
                ('zdjecie', models.ImageField(upload_to='car_pics')),
                ('data_dodania', models.DateField()),
                ('data_publikacji', models.DateField(blank=True, default=None, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),),
                'abstract': False,
            },
        ),
    ]
